### PR TITLE
add push notif to discord

### PR DESCRIPTION
**Pull request by titan2903**

### CODE REVIEW

**Comment by titan2903** [comment]
Ran Plan for 3 projects:

1. dir: `terragrunt/production/instances/instance-awx` workspace: `default`
1. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`
1. dir: `terragrunt/staging/vpc-networks` workspace: `default`

### 1. dir: `terragrunt/production/instances/instance-awx` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-18T10:54:26Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/production/instances/instance-awx] 
time=2023-12-18T10:54:26Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/production/instances/instance-awx] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.google_compute_address.external_static_ip: Reading...
data.google_compute_address.external_static_ip: Read complete after 0s [id=projects/fundhub-408000/regions/asia-southeast2/addresses/static-ip-awx]
google_compute_instance.default: Refreshing state... [id=projects/fundhub-408000/zones/asia-southeast2-a/instances/instance-awx]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/production/instances/instance-awx`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fproduction%252Finstances%252Finstance-awx%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/production/instances/instance-awx`
</details>
No changes. Your infrastructure matches the configuration.

---
### 2. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-18T10:54:33Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 
time=2023-12-18T10:54:33Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_address.static_ip will be created
  + resource "google_compute_address" "static_ip" {
      + address            = (known after apply)
      + address_type       = "EXTERNAL"
      + creation_timestamp = (known after apply)
      + effective_labels   = (known after apply)
      + id                 = (known after apply)
      + label_fingerprint  = (known after apply)
      + name               = "static-ip-mariadb"
      + network_tier       = (known after apply)
      + prefix_length      = (known after apply)
      + project            = "fundhub-staging"
      + purpose            = (known after apply)
      + region             = "asia-southeast2"
      + self_link          = (known after apply)
      + subnetwork         = (known after apply)
      + terraform_labels   = (known after apply)
      + users              = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Saved the plan to:
/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb/default.tfplan"
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/vpc-networks/static-ip-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Fvpc-networks%252Fstatic-ip-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/vpc-networks/static-ip-mariadb`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 3. dir: `terragrunt/staging/vpc-networks` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks": exit status 1: running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks": 
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.

Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.
time=2023-12-18T10:54:41Z level=error msg=terraform invocation failed in /root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks
time=2023-12-18T10:54:41Z level=error msg=1 error occurred:
	* [/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks] exit status 1



time=2023-12-18T10:54:41Z level=warning msg=The following inputs passed in by terragrunt are unused:

time=2023-12-18T10:54:41Z level=warning msg=	- address_type
time=2023-12-18T10:54:41Z level=warning msg=	- credentials
time=2023-12-18T10:54:41Z level=warning msg=	- name
time=2023-12-18T10:54:41Z level=warning msg=	- project_id
time=2023-12-18T10:54:41Z level=warning msg=	- region
time=2023-12-18T10:54:41Z level=warning msg=	- zone
time=2023-12-18T10:54:41Z level=warning
time=2023-12-18T10:54:41Z level=info msg=All required inputs are passed in by terragrunt
time=2023-12-18T10:54:41Z level=warning msg=Terragrunt configuration has misaligned inputs, but running in relaxed mode so ignoring.

```
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by titanioy — APPROVED** [review]

**Comment by titan2903** [comment]
atlantis apply

**Comment by titan2903** [comment]
Ran Apply for 2 projects:

1. dir: `terragrunt/production/instances/instance-awx` workspace: `default`
1. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

### 1. dir: `terragrunt/production/instances/instance-awx` workspace: `default`
```diff
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

private_ip = "10.184.0.22"
public_ip = "34.101.142.147"
```

---
### 2. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`
**Apply Error**
<details><summary>Show Output</summary>

```
running "terragrunt apply --terragrunt-non-interactive -no-color $PLANFILE" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb": exit status 1: running "terragrunt apply --terragrunt-non-interactive -no-color $PLANFILE" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb": 
google_compute_address.static_ip: Creating...

Error: Error creating Address: googleapi: Error 409: The resource 'projects/fundhub-staging/regions/asia-southeast2/addresses/static-ip-mariadb' already exists, alreadyExists

  with google_compute_address.static_ip,
  on main.tf line 18, in resource "google_compute_address" "static_ip":
  18: resource "google_compute_address" "static_ip" {

time=2023-12-18T10:55:43Z level=error msg=terraform invocation failed in /root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb/.terragrunt-cache/oQpwIlAyr2E6NMPVnTN6kvSI0L8/K24t9kdKa22qISF59nhOrQ2CFPQ prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 
time=2023-12-18T10:55:43Z level=error msg=1 error occurred:
	* [/root/.atlantis/repos/titan2903/fundhub-terraform-config/5/default/terragrunt/staging/vpc-networks/static-ip-mariadb/.terragrunt-cache/oQpwIlAyr2E6NMPVnTN6kvSI0L8/K24t9kdKa22qISF59nhOrQ2CFPQ] exit status 1




```
</details>

---

**Comment by titan2903** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terragrunt/production/instances/instance-awx` workspace: `default`
- dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

**Pull request merged**
