### PR TITLE
Setup vm instances

### PR DESCRIPTION
**Pull request by titan2903**

### CODE REVIEW

**Comment by titan2903** [comment]
Ran Plan for 3 projects:

1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
1. dir: `terragrunt/staging/instances` workspace: `default`
1. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

### 1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-17T06:10:03Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb] 
time=2023-12-17T06:10:03Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
  + resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + effective_labels     = (known after apply)
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-micro"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "instance-mariadb"
      + project              = "fundhub-staging"
      + self_link            = (known after apply)
      + tags                 = [
          + "allow-specific-port",
        ]
      + tags_fingerprint     = (known after apply)
      + terraform_labels     = (known after apply)
      + zone                 = "asia-southeast2-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "ubuntu-os-cloud/ubuntu-2204-lts"
              + labels = (known after apply)
              + size   = (known after apply)
              + type   = (known after apply)
            }
        }

      + network_interface {
          + internal_ipv6_prefix_length = (known after apply)
          + ipv6_access_type            = (known after apply)
          + ipv6_address                = (known after apply)
          + name                        = (known after apply)
          + network                     = "default"
          + network_ip                  = (known after apply)
          + stack_type                  = (known after apply)
          + subnetwork                  = "default"
          + subnetwork_project          = (known after apply)

          + access_config {
              + nat_ip       = (known after apply)
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + private_ip = (known after apply)
  + public_ip  = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to:
/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb/default.tfplan"
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/instances/instance-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Finstances%252Finstance-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/instances/instance-mariadb`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `terragrunt/staging/instances` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances": exit status 1: running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances": 
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.

Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.
time=2023-12-17T06:10:09Z level=error msg=terraform invocation failed in /root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances
time=2023-12-17T06:10:09Z level=error msg=1 error occurred:
	* [/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances] exit status 1



time=2023-12-17T06:10:08Z level=warning msg=The following inputs passed in by terragrunt are unused:

time=2023-12-17T06:10:08Z level=warning msg=	- region
time=2023-12-17T06:10:08Z level=warning msg=	- zone
time=2023-12-17T06:10:08Z level=warning msg=	- credentials
time=2023-12-17T06:10:08Z level=warning msg=	- name
time=2023-12-17T06:10:08Z level=warning msg=	- project_id
time=2023-12-17T06:10:08Z level=warning
time=2023-12-17T06:10:08Z level=info msg=All required inputs are passed in by terragrunt
time=2023-12-17T06:10:08Z level=warning msg=Terragrunt configuration has misaligned inputs, but running in relaxed mode so ignoring.

```
</details>

---
### 3. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-17T06:10:10Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 
time=2023-12-17T06:10:10Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
google_compute_address.static_ip: Refreshing state... [id=projects/fundhub-staging/regions/asia-southeast2/addresses/static-ip-mariadb]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/vpc-networks/static-ip-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Fvpc-networks%252Fstatic-ip-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/vpc-networks/static-ip-mariadb`
</details>
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by titan2903** [comment]
Ran Plan for 3 projects:

1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
1. dir: `terragrunt/staging/instances` workspace: `default`
1. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

### 1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-17T06:15:45Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb] 
time=2023-12-17T06:15:45Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.google_compute_address.external_static_ip: Reading...
data.google_compute_address.external_static_ip: Read complete after 0s [id=projects/fundhub-staging/regions/asia-southeast2/addresses/static-ip-mariadb]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
  + resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + effective_labels     = (known after apply)
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-micro"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "instance-mariadb"
      + project              = "fundhub-staging"
      + self_link            = (known after apply)
      + tags                 = [
          + "allow-specific-port",
        ]
      + tags_fingerprint     = (known after apply)
      + terraform_labels     = (known after apply)
      + zone                 = "asia-southeast2-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "ubuntu-os-cloud/ubuntu-2204-lts"
              + labels = (known after apply)
              + size   = 35
              + type   = (known after apply)
            }
        }

      + network_interface {
          + internal_ipv6_prefix_length = (known after apply)
          + ipv6_access_type            = (known after apply)
          + ipv6_address                = (known after apply)
          + name                        = (known after apply)
          + network                     = "default"
          + network_ip                  = (known after apply)
          + stack_type                  = (known after apply)
          + subnetwork                  = "default"
          + subnetwork_project          = (known after apply)

          + access_config {
              + nat_ip       = "34.101.228.83"
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + private_ip = (known after apply)
  + public_ip  = "34.101.228.83"

─────────────────────────────────────────────────────────────────────────────

Saved the plan to:
/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb/default.tfplan"
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/instances/instance-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Finstances%252Finstance-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/instances/instance-mariadb`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `terragrunt/staging/instances` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances": exit status 1: running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances": 
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.

Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.
time=2023-12-17T06:15:51Z level=error msg=terraform invocation failed in /root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances
time=2023-12-17T06:15:51Z level=error msg=1 error occurred:
	* [/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances] exit status 1



time=2023-12-17T06:15:50Z level=warning msg=The following inputs passed in by terragrunt are unused:

time=2023-12-17T06:15:50Z level=warning msg=	- project_id
time=2023-12-17T06:15:50Z level=warning msg=	- region
time=2023-12-17T06:15:50Z level=warning msg=	- zone
time=2023-12-17T06:15:50Z level=warning msg=	- credentials
time=2023-12-17T06:15:50Z level=warning msg=	- name
time=2023-12-17T06:15:50Z level=warning
time=2023-12-17T06:15:50Z level=info msg=All required inputs are passed in by terragrunt
time=2023-12-17T06:15:50Z level=warning msg=Terragrunt configuration has misaligned inputs, but running in relaxed mode so ignoring.

```
</details>

---
### 3. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-17T06:15:52Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 
time=2023-12-17T06:15:52Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
google_compute_address.static_ip: Refreshing state... [id=projects/fundhub-staging/regions/asia-southeast2/addresses/static-ip-mariadb]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/vpc-networks/static-ip-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Fvpc-networks%252Fstatic-ip-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/vpc-networks/static-ip-mariadb`
</details>
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by titanioy — APPROVED** [review]

**Comment by titan2903** [comment]
Ran Plan for 3 projects:

1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
1. dir: `terragrunt/staging/instances` workspace: `default`
1. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

### 1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-17T06:54:33Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb] 
time=2023-12-17T06:54:33Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.google_compute_address.external_static_ip: Reading...
data.google_compute_address.external_static_ip: Read complete after 0s [id=projects/fundhub-staging/regions/asia-southeast2/addresses/static-ip-mariadb]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
  + resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + effective_labels     = (known after apply)
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-micro"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "instance-mariadb"
      + project              = "fundhub-staging"
      + self_link            = (known after apply)
      + tags                 = [
          + "allow-specific-port",
        ]
      + tags_fingerprint     = (known after apply)
      + terraform_labels     = (known after apply)
      + zone                 = "asia-southeast2-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "ubuntu-os-cloud/ubuntu-2204-lts"
              + labels = (known after apply)
              + size   = 35
              + type   = (known after apply)
            }
        }

      + network_interface {
          + internal_ipv6_prefix_length = (known after apply)
          + ipv6_access_type            = (known after apply)
          + ipv6_address                = (known after apply)
          + name                        = (known after apply)
          + network                     = "default"
          + network_ip                  = (known after apply)
          + stack_type                  = (known after apply)
          + subnetwork                  = "default"
          + subnetwork_project          = (known after apply)

          + access_config {
              + nat_ip       = "34.101.228.83"
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + private_ip = (known after apply)
  + public_ip  = "34.101.228.83"

─────────────────────────────────────────────────────────────────────────────

Saved the plan to:
/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances/instance-mariadb/default.tfplan"
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/instances/instance-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Finstances%252Finstance-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/instances/instance-mariadb`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `terragrunt/staging/instances` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances": exit status 1: running "terragrunt plan --terragrunt-non-interactive -no-color -out=$PLANFILE $DESTROY_PARAMETER" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances": 
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.

Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.
time=2023-12-17T06:54:39Z level=error msg=terraform invocation failed in /root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances
time=2023-12-17T06:54:39Z level=error msg=1 error occurred:
	* [/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/instances] exit status 1



time=2023-12-17T06:54:39Z level=warning msg=The following inputs passed in by terragrunt are unused:

time=2023-12-17T06:54:39Z level=warning msg=	- region
time=2023-12-17T06:54:39Z level=warning msg=	- sub_network
time=2023-12-17T06:54:39Z level=warning msg=	- zone
time=2023-12-17T06:54:39Z level=warning msg=	- credentials
time=2023-12-17T06:54:39Z level=warning msg=	- name
time=2023-12-17T06:54:39Z level=warning msg=	- network
time=2023-12-17T06:54:39Z level=warning msg=	- project_id
time=2023-12-17T06:54:39Z level=warning
time=2023-12-17T06:54:39Z level=info msg=All required inputs are passed in by terragrunt
time=2023-12-17T06:54:39Z level=warning msg=Terragrunt configuration has misaligned inputs, but running in relaxed mode so ignoring.

```
</details>

---
### 3. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-17T06:54:40Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 
time=2023-12-17T06:54:40Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/3/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
google_compute_address.static_ip: Refreshing state... [id=projects/fundhub-staging/regions/asia-southeast2/addresses/static-ip-mariadb]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/vpc-networks/static-ip-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Fvpc-networks%252Fstatic-ip-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/vpc-networks/static-ip-mariadb`
</details>
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by titan2903** [comment]
atlantis apply

**Comment by titan2903** [comment]
Ran Apply for 2 projects:

1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
1. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

### 1. dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
```diff
google_compute_instance.default: Creating...
google_compute_instance.default: Still creating... [10s elapsed]
google_compute_instance.default: Creation complete after 15s [id=projects/fundhub-staging/zones/asia-southeast2-a/instances/instance-mariadb]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

private_ip = "10.184.0.2"
public_ip = "34.101.228.83"
```

---
### 2. dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`
```diff
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

---

**Comment by titan2903** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terragrunt/staging/instances/instance-mariadb` workspace: `default`
- dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

**Pull request merged**
