### PR TITLE
change machine_type and boot_disk_size_gb value

### PR DESCRIPTION
**Pull request by titan2903**
- Change specification compute engine Jenkins agents

### CODE REVIEW

**Comment by titan2903** [comment]
Ran Plan for 2 projects:

1. dir: `terragrunt/production/instances/instance-fire-agent` workspace: `default`
1. dir: `terragrunt/production/instances/instance-sandbox-agent` workspace: `default`

### 1. dir: `terragrunt/production/instances/instance-fire-agent` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-19T03:08:16Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-fire-agent] 
time=2023-12-19T03:08:16Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-fire-agent] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.google_compute_address.external_static_ip: Reading...
data.google_compute_address.external_static_ip: Read complete after 0s [id=projects/fundhub-408000/regions/asia-southeast2/addresses/static-ip-jenkins-agent-fire]
google_compute_instance.default: Refreshing state... [id=projects/fundhub-408000/zones/asia-southeast2-a/instances/instance-fire-agent]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # google_compute_instance.default has been deleted
  - resource "google_compute_instance" "default" {
        id                   = "projects/fundhub-408000/zones/asia-southeast2-a/instances/instance-fire-agent"
        name                 = "instance-fire-agent"
        tags                 = [
            "allow-specific-port",
        ]
        # (19 unchanged attributes hidden)

      - network_interface {
            name                        = "nic0"
          - network_ip                  = "10.184.0.23" -> null
            # (6 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
  + resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + effective_labels     = (known after apply)
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-medium"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "instance-fire-agent"
      + project              = "fundhub-408000"
      + self_link            = (known after apply)
      + tags                 = [
          + "allow-specific-port",
        ]
      + tags_fingerprint     = (known after apply)
      + terraform_labels     = (known after apply)
      + zone                 = "asia-southeast2-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "ubuntu-os-cloud/ubuntu-2204-lts"
              + labels = (known after apply)
              + size   = 55
              + type   = (known after apply)
            }
        }

      + network_interface {
          + internal_ipv6_prefix_length = (known after apply)
          + ipv6_access_type            = (known after apply)
          + ipv6_address                = (known after apply)
          + name                        = (known after apply)
          + network                     = "default"
          + network_ip                  = (known after apply)
          + stack_type                  = (known after apply)
          + subnetwork                  = "default"
          + subnetwork_project          = (known after apply)

          + access_config {
              + nat_ip       = "34.101.54.71"
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ private_ip = "10.184.0.23" -> (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to:
/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-fire-agent/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-fire-agent/default.tfplan"
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/production/instances/instance-fire-agent`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fproduction%252Finstances%252Finstance-fire-agent%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/production/instances/instance-fire-agent`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `terragrunt/production/instances/instance-sandbox-agent` workspace: `default`
<details><summary>Show Output</summary>

```diff
time=2023-12-19T03:08:22Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-sandbox-agent] 
time=2023-12-19T03:08:22Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-sandbox-agent] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.google_compute_address.external_static_ip: Reading...
data.google_compute_address.external_static_ip: Read complete after 0s [id=projects/fundhub-408000/regions/asia-southeast2/addresses/static-ip-jenkins-agent-sandbox]
google_compute_instance.default: Refreshing state... [id=projects/fundhub-408000/zones/asia-southeast2-a/instances/instance-sandbox-agent]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # google_compute_instance.default has been deleted
  - resource "google_compute_instance" "default" {
        id                   = "projects/fundhub-408000/zones/asia-southeast2-a/instances/instance-sandbox-agent"
        name                 = "instance-sandbox-agent"
        tags                 = [
            "allow-specific-port",
        ]
        # (16 unchanged attributes hidden)

      - network_interface {
            name                        = "nic0"
          - network_ip                  = "10.184.0.26" -> null
            # (6 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
  + resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + effective_labels     = (known after apply)
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-medium"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "instance-sandbox-agent"
      + project              = "fundhub-408000"
      + self_link            = (known after apply)
      + tags                 = [
          + "allow-specific-port",
        ]
      + tags_fingerprint     = (known after apply)
      + terraform_labels     = (known after apply)
      + zone                 = "asia-southeast2-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "ubuntu-os-cloud/ubuntu-2204-lts"
              + labels = (known after apply)
              + size   = 55
              + type   = (known after apply)
            }
        }

      + network_interface {
          + internal_ipv6_prefix_length = (known after apply)
          + ipv6_access_type            = (known after apply)
          + ipv6_address                = (known after apply)
          + name                        = (known after apply)
          + network                     = "default"
          + network_ip                  = (known after apply)
          + stack_type                  = (known after apply)
          + subnetwork                  = "default"
          + subnetwork_project          = (known after apply)

          + access_config {
              + nat_ip       = "34.101.199.35"
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ private_ip = "10.184.0.26" -> (known after apply)

─────────────────────────────────────────────────────────────────────────────

Saved the plan to:
/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-sandbox-agent/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/titan2903/fundhub-terraform-config/8/default/terragrunt/production/instances/instance-sandbox-agent/default.tfplan"
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/production/instances/instance-sandbox-agent`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fproduction%252Finstances%252Finstance-sandbox-agent%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/production/instances/instance-sandbox-agent`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by titanioy — APPROVED** [review]

**Comment by titan2903** [comment]
atlantis apply

**Comment by titan2903** [comment]
Ran Apply for 2 projects:

1. dir: `terragrunt/production/instances/instance-fire-agent` workspace: `default`
1. dir: `terragrunt/production/instances/instance-sandbox-agent` workspace: `default`

### 1. dir: `terragrunt/production/instances/instance-fire-agent` workspace: `default`
```diff
google_compute_instance.default: Creating...
google_compute_instance.default: Still creating... [10s elapsed]
google_compute_instance.default: Creation complete after 14s [id=projects/fundhub-408000/zones/asia-southeast2-a/instances/instance-fire-agent]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

private_ip = "10.184.0.27"
public_ip = "34.101.54.71"
```

---
### 2. dir: `terragrunt/production/instances/instance-sandbox-agent` workspace: `default`
```diff
google_compute_instance.default: Creating...
google_compute_instance.default: Still creating... [10s elapsed]
google_compute_instance.default: Creation complete after 13s [id=projects/fundhub-408000/zones/asia-southeast2-a/instances/instance-sandbox-agent]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

private_ip = "10.184.0.28"
public_ip = "34.101.199.35"
```

---

**Comment by titan2903** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terragrunt/production/instances/instance-fire-agent` workspace: `default`
- dir: `terragrunt/production/instances/instance-sandbox-agent` workspace: `default`

**Pull request merged**
