### PR TITLE
Feature/discord push notif

### PR DESCRIPTION
**Pull request by titan2903**

### CODE REVIEW

**Comment by titan2903** [comment]
Ran Plan for dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

<details><summary>Show Output</summary>

```diff
time=2023-12-18T11:15:30Z level=info msg=All variables passed in by terragrunt are in use. prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 
time=2023-12-18T11:15:30Z level=info msg=All required inputs are passed in by terragrunt prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 


Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/google versions matching "5.9.0"...
- Installing hashicorp/google v5.9.0...
- Installed hashicorp/google v5.9.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_compute_address.static_ip will be created
  + resource "google_compute_address" "static_ip" {
      + address            = (known after apply)
      + address_type       = "EXTERNAL"
      + creation_timestamp = (known after apply)
      + effective_labels   = (known after apply)
      + id                 = (known after apply)
      + label_fingerprint  = (known after apply)
      + name               = "static-ip-mariadb"
      + network_tier       = (known after apply)
      + prefix_length      = (known after apply)
      + project            = "fundhub-staging"
      + purpose            = (known after apply)
      + region             = "asia-southeast2"
      + self_link          = (known after apply)
      + subnetwork         = (known after apply)
      + terraform_labels   = (known after apply)
      + users              = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Saved the plan to:
/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb/default.tfplan"
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terragrunt/staging/vpc-networks/static-ip-mariadb`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.128.65.188/lock?id=titan2903%252Ffundhub-terraform-config%252Fterragrunt%252Fstaging%252Fvpc-networks%252Fstatic-ip-mariadb%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terragrunt/staging/vpc-networks/static-ip-mariadb`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by titanioy — APPROVED** [review]

**Comment by titan2903** [comment]
atlantis apply

**Comment by titan2903** [comment]
Ran Apply for dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "terragrunt apply --terragrunt-non-interactive -no-color $PLANFILE" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb": exit status 1: running "terragrunt apply --terragrunt-non-interactive -no-color $PLANFILE" in "/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb": 
google_compute_address.static_ip: Creating...

Error: Error creating Address: googleapi: Error 409: The resource 'projects/fundhub-staging/regions/asia-southeast2/addresses/static-ip-mariadb' already exists, alreadyExists

  with google_compute_address.static_ip,
  on main.tf line 18, in resource "google_compute_address" "static_ip":
  18: resource "google_compute_address" "static_ip" {

time=2023-12-18T11:17:07Z level=error msg=terraform invocation failed in /root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb/.terragrunt-cache/7KoPoLJYgHn0Y1Te3eElI-hwxmw/TGzMrfV9ouWwnc--NUKLHdvSsCY prefix=[/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb] 
time=2023-12-18T11:17:07Z level=error msg=1 error occurred:
	* [/root/.atlantis/repos/titan2903/fundhub-terraform-config/6/default/terragrunt/staging/vpc-networks/static-ip-mariadb/.terragrunt-cache/7KoPoLJYgHn0Y1Te3eElI-hwxmw/TGzMrfV9ouWwnc--NUKLHdvSsCY] exit status 1




```
</details>

**Comment by titan2903** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terragrunt/staging/vpc-networks/static-ip-mariadb` workspace: `default`

**Pull request merged**
